### ISSUE TITLE
Add ability to mark attributes optional (Providerfile.yml)

### ISSUE THREAD

**Issue by gkra** [vaquero-io/vaquero_io#25]
Add the ability to allow attributes to be optional in `platform.yml` so that they can be checked for correctness if present, but will not cause a health check to fail if they are missing. This would likely entail adding an option to the `Providerfile.yml`, possibly a `required` parameter:

``` yaml
provider:
  structure:
    platform:
      params:
        run_list:
          required: true
          array:
            type: string
            match: '(role|recipe)\[([-_a-zA-Z0-9]+)\]'
        component_role:
          required: false
          type: string
          match: '(role|recipe)\[([-_a-zA-Z0-9#]+)\]'
```

In this example, then, `vaquero_io` would require `run_list` to be present and match the constraints for every component, but `component_role` will only cause a failure if it is present and does not match.
